application:
  message: "Welcome To local property from config server"

spring:
  application:
    name: cloud-service-empty
  config:
    import: optional:configserver:${spring.cloud.config.uri}
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8071
    stream:
      bindings:
        gradesChannel-in-0:
          destination: GradesExchange
          group: grades-updates
          consumer:
            concurrency: 10
            max-attempts: 3
      rabbit:
        bindings:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring.cloud.stream.bindings.output.destination: orgChangeTopic
spring.cloud.stream.bindings.output.content-type: application/json

