application:
  message: "Welcome To local property from config server"


spring:
  application:
    name: cloud-service-config-client
  config:
    import: optional:configserver:${spring.cloud.config.uri}
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8071
server:
  port: 8090


spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/auth/realms/master

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
