management.endpoints.web.exposure.include: "*"
management.endpoints.enabled-by-default: "true"

application:
  message: "Welcome To local property from config server"
server:
  port: 8081 # 8080
spring:
  application:
    name: eureka-client
  config:
    import: optional:configserver:${spring.cloud.config.uri}
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8071

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"
