application:
  message: "Welcome To local property from config server"

spring:
  application:
    name: cloud-service-stream-kafka
  config:
    import: optional:configserver:${spring.cloud.config.uri}
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8071

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring.cloud.stream.bindings.output.destination: orgChangeTopic
spring.cloud.stream.bindings.output.content-type: application/json
spring.cloud.stream.kafka.binder.zkNodes: localhost
spring.cloud.stream.kafka.binder.brokers: localhost
