spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
  config:
    import: optional:configserver:${spring.cloud.config.uri}
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8071
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"

