SET FOREIGN_KEY_CHECKS = 0;
drop table if exists `activity`;
drop table IF EXISTS `user`;
drop table IF EXISTS `document`;
drop table IF EXISTS `countryTranslation`;
drop table IF EXISTS `country`;
drop table IF EXISTS `timezoneTranslation`;
drop table IF EXISTS `timezone`;
drop table IF EXISTS `themeTranslation`;
drop table IF EXISTS `theme`;
drop table IF EXISTS `languageTranslation`;
drop table IF EXISTS `language`;
SET FOREIGN_KEY_CHECKS = 1;