-- Insert themes:
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('cerulean','Cerulean');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('cosmo','Cosmo');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('cyborg','Cyborg');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('darkly','Darkly');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('default','Default');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('flatly','Flatly');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('journal','Journal');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('litera','Litera');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('lumen','Lumen');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('lux','Lux');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('materia','Materia');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('minty','Minty');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('pulse','Pulse');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('sandstone','Sandstone');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('simplex','Simplex');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('sketchy','Sketchy');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('slate','Slate');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('solar','Solar');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('spacelab','Spacelab');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('superhero','Superhero');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('united','United');
INSERT INTO `theme` (`themeId`, `themeName`) VALUES ('yeti','Yeti');

-- Insert languages:
INSERT INTO `language` (`languageId`, `languageName`) VALUES ('ar','Arabic (AR)');
INSERT INTO `language` (`languageId`, `languageName`) VALUES ('en','English (EN)');

-- Insert Countries:
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AD','Andorra');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AE','United Arab Emirates');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AF','Afghanistan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AI','Anguilla');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AL','Albania');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AM','Armenia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AN','Netherlands Antilles');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AO','Angola');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AR','Argentina');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AS','American Samoa');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AT','Austria');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AU','Australia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AW','Aruba');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('AZ','Azerbaijan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BA','Bosnia and Herzegowina');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BB','Barbados');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BD','Bangladesh');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BE','Belgium');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BF','Burkina Faso');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BG','Bulgaria');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BH','Bahrain');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BI','Burundi');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BJ','Benin');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BL','Saint Barthelemy');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BM','Bermuda');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BN','Brunei Darussalam');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BO','Bolivia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BR','Brazil');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BS','Bahamas');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BT','Bhutan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BV','Bouvet Island');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BW','Botswana');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BY','Belarus');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('BZ','Belize');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CA','Canada');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CC','Cocos (Keeling) Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CD','Congo, the Democratic Republic of the');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CF','Central African Republic');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CG','Congo');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CH','Switzerland');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CI','Cote d\'Ivoire');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CK','Cook Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CL','Chile');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CM','Cameroon');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CN','China');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CO','Colombia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CR','Costa Rica');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CU','Cuba');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CV','Cape Verde');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CX','Christmas Island');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CY','Cyprus');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('CZ','Czech Republic');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('DE','Germany');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('DJ','Djibouti');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('DK','Denmark');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('DM','Dominica');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('DO','Dominican Republic');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('DZ','Algeria');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('EC','Ecuador');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('EE','Estonia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('EG','Egypt');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('EH','Western Sahara');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ER','Eritrea');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ES','Spain');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ET','Ethiopia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('FI','Finland');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('FJ','Fiji');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('FK','Falkland Islands (Malvinas)');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('FM','Micronesia, Federated States of');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('FO','Faroe Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('FR','France');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GA','Gabon');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GB','United Kingdom');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GD','Grenada');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GE','Georgia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GF','French Guiana');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GH','Ghana');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GI','Gibraltar');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GL','Greenland');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GM','Gambia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GN','Guinea');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GP','Guadeloupe');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GQ','Equatorial Guinea');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GR','Greece');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GS','South Georgia and the South Sandwich Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GT','Guatemala');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GU','Guam');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GW','Guinea-Bissau');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('GY','Guyana');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('HK','Hong Kong');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('HM','Heard and Mc Donald Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('HN','Honduras');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('HR','Croatia (Hrvatska)');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('HT','Haiti');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('HU','Hungary');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ID','Indonesia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('IE','Ireland');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('IL','Israel');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('IN','India');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('IO','British Indian Ocean Territory');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('IQ','Iraq');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('IR','Iran (Islamic Republic of)');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('IS','Iceland');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('IT','Italy');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('JM','Jamaica');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('JO','Jordan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('JP','Japan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KE','Kenya');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KG','Kyrgyzstan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KH','Cambodia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KI','Kiribati');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KM','Comoros');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KN','Saint Kitts and Nevis');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KP','Korea, Democratic People\'s Republic of');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KR','Korea, Republic of');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KW','Kuwait');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KY','Cayman Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('KZ','Kazakhstan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LA','Lao People\'s Democratic Republic');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LB','Lebanon');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LC','Saint LUCIA');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LI','Liechtenstein');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LK','Sri Lanka');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LR','Liberia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LS','Lesotho');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LT','Lithuania');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LU','Luxembourg');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LV','Latvia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('LY','Libyan Arab Jamahiriya');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MA','Morocco');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MC','Monaco');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MD','Moldova, Republic of');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MG','Madagascar');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MH','Marshall Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MK','Macedonia, The Former Yugoslav Republic of');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ML','Mali');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MM','Myanmar');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MN','Mongolia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MO','Macau');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MP','Northern Mariana Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MQ','Martinique');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MR','Mauritania');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MS','Montserrat');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MT','Malta');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MU','Mauritius');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MV','Maldives');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MW','Malawi');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MX','Mexico');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MY','Malaysia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('MZ','Mozambique');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NA','Namibia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NC','New Caledonia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NE','Niger');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NF','Norfolk Island');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NG','Nigeria');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NI','Nicaragua');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NL','Netherlands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NO','Norway');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NP','Nepal');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NR','Nauru');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NU','Niue');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('NZ','New Zealand');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('OM','Oman');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PA','Panama');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PE','Peru');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PF','French Polynesia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PG','Papua New Guinea');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PH','Philippines');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PK','Pakistan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PL','Poland');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PM','St. Pierre and Miquelon');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PN','Pitcairn');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PR','Puerto Rico');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PT','Portugal');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PW','Palau');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('PY','Paraguay');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('QA','Qatar');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('RE','Reunion');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('RO','Romania');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('RU','Russian Federation');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('RW','Rwanda');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SA','Saudi Arabia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SB','Solomon Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SC','Seychelles');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SD','Sudan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SE','Sweden');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SG','Singapore');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SH','St. Helena');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SI','Slovenia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SJ','Svalbard and Jan Mayen Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SK','Slovakia (Slovak Republic)');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SL','Sierra Leone');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SM','San Marino');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SN','Senegal');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SO','Somalia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SR','Suriname');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ST','Sao Tome and Principe');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SV','El Salvador');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SY','Syrian Arab Republic');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('SZ','Swaziland');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TC','Turks and Caicos Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TD','Chad');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TF','French Southern Territories');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TG','Togo');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TH','Thailand');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TJ','Tajikistan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TK','Tokelau');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TM','Turkmenistan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TN','Tunisia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TO','Tonga');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TR','Turkey');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TT','Trinidad and Tobago');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TV','Tuvalu');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TW','Taiwan, Province of China');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('TZ','Tanzania, United Republic of');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('UA','Ukraine');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('UG','Uganda');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('UM','United States Minor Outlying Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('US','United States');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('UY','Uruguay');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('UZ','Uzbekistan');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('VA','Holy See (Vatican City State)');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('VC','Saint Vincent and the Grenadines');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('VE','Venezuela');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('VG','Virgin Islands (British)');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('VI','Virgin Islands (U.S.)');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('VN','Viet Nam');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('VU','Vanuatu');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('WF','Wallis and Futuna Islands');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('WS','Samoa');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('YE','Yemen');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('YT','Mayotte');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ZA','South Africa');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ZM','Zambia');
INSERT INTO `country` (`countryId`, `countryName`) VALUES ('ZW','Zimbabwe');